steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rock-partition-363003/python-application', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/rock-partition-363003/python-application']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'python-application', '--image', 'gcr.io/rock-partition-363003/python-application', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/rock-partition-363003/python-application
